[[main]]
none = "none"

[[main]]
name = "Home"
pageRef = "/"
identifier = "FKEszI1rPZ"
weight = 7

[[main]]
name = "Articles"
pageRef = "/posts"
identifier = "yr6CO5lK5F"
weight = 6

[[main]]
name = "Linux"
pageRef = "/posts/linux"
parent = "Categories"
weight = 1

[[main]]
name = "openSUSE"
pageRef = "/posts/opensuse"
parent = "Categories"
weight = 2

[[main]]
name = "WSL"
pageRef = "/posts/wsl"
parent = "Categories"
weight = 3

[[main]]
name = "Quicky"
pageRef = "/posts/quicky"
parent = "Categories"
weight = 4

[[main]]
name = "Various Stuff"
pageRef = "/posts/stuff"
parent = "Categories"
weight = 5

[[main]]
name = "Browse Tags"
pageRef = "/tags"
parent = "Categories"
weight = 6

[[footer]]
none = "none"
